cmd_/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/weak.o := gcc -Wp,-MD,/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/.weak.o.d -Wp,-MT,/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/weak.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wno-type-limits -Wstrict-aliasing=3 -Wshadow -Wno-switch-default -Wno-switch-enum -Wno-packed -Wno-nested-externs -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -Wdeclaration-after-statement -g -I/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include -I/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/arch/x86/include/uapi -I/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/arch/x86/include -I/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/include -I/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/arch/x86/include -I/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/libsubcmd/include -D"BUILD_STR(s)=$(pound)s" -c -o /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/weak.o weak.c

source_/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/weak.o := weak.c

deps_/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/weak.o := \
  /usr/include/stdc-predef.h \
  /usr/lib/gcc/x86_64-linux-gnu/12/include/stdbool.h \
  /usr/include/errno.h \
  /usr/include/features.h \
  /usr/include/features-time64.h \
  /usr/include/x86_64-linux-gnu/bits/wordsize.h \
  /usr/include/x86_64-linux-gnu/bits/timesize.h \
  /usr/include/x86_64-linux-gnu/sys/cdefs.h \
  /usr/include/x86_64-linux-gnu/bits/long-double.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs.h \
  /usr/include/x86_64-linux-gnu/gnu/stubs-64.h \
  /usr/include/x86_64-linux-gnu/bits/errno.h \
  /usr/include/linux/errno.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/arch/x86/include/uapi/asm/errno.h \
  /usr/include/asm-generic/errno.h \
  /usr/include/asm-generic/errno-base.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/include/objtool/objtool.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/list.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-linux-gnu/12/include/stddef.h \
  /usr/lib/gcc/x86_64-linux-gnu/12/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/x86_64-linux-gnu/bits/libc-header-start.h \
  /usr/include/x86_64-linux-gnu/bits/types.h \
  /usr/include/x86_64-linux-gnu/bits/typesizes.h \
  /usr/include/x86_64-linux-gnu/bits/time64.h \
  /usr/include/x86_64-linux-gnu/bits/wchar.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-intn.h \
  /usr/include/x86_64-linux-gnu/bits/stdint-uintn.h \
  /usr/include/x86_64-linux-gnu/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitsperlong.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types.h \
  /usr/include/x86_64-linux-gnu/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/poison.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/kernel.h \
  /usr/lib/gcc/x86_64-linux-gnu/12/include/stdarg.h \
  /usr/include/assert.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/build_bug.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/compiler.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/compiler_types.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/compiler-gcc.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/math.h \
  /usr/include/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endian.h \
  /usr/include/x86_64-linux-gnu/bits/endianness.h \
  /usr/include/x86_64-linux-gnu/bits/byteswap.h \
  /usr/include/x86_64-linux-gnu/bits/uintn-identity.h \
  /usr/include/byteswap.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/hashtable.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/bitops.h \
  /usr/lib/gcc/x86_64-linux-gnu/12/include/limits.h \
  /usr/lib/gcc/x86_64-linux-gnu/12/include/syslimits.h \
  /usr/include/limits.h \
  /usr/include/x86_64-linux-gnu/bits/posix1_lim.h \
  /usr/include/x86_64-linux-gnu/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/x86_64-linux-gnu/bits/pthread_stack_min-dynamic.h \
  /usr/include/x86_64-linux-gnu/bits/pthread_stack_min.h \
  /usr/include/x86_64-linux-gnu/bits/posix2_lim.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/bits.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/const.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/vdso/const.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/uapi/linux/const.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/vdso/bits.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops/__ffs.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops/__ffz.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops/fls.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops/__fls.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops/fls64.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops/hweight.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops/arch_hweight.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops/const_hweight.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops/atomic.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/asm-generic/bitops/non-atomic.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/hash.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/log2.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/include/objtool/elf.h \
  /usr/include/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/FILE.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h \
  /usr/include/x86_64-linux-gnu/bits/stdio_lim.h \
  /usr/include/x86_64-linux-gnu/bits/floatn.h \
  /usr/include/x86_64-linux-gnu/bits/floatn-common.h \
  /usr/include/x86_64-linux-gnu/bits/stdio2-decl.h \
  /usr/include/x86_64-linux-gnu/bits/stdio.h \
  /usr/include/x86_64-linux-gnu/bits/stdio2.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/include/x86_64-linux-gnu/sys/types.h \
  /usr/include/x86_64-linux-gnu/bits/types/clock_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/clockid_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/time_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/timer_t.h \
  /usr/include/x86_64-linux-gnu/sys/select.h \
  /usr/include/x86_64-linux-gnu/bits/select.h \
  /usr/include/x86_64-linux-gnu/bits/types/sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/__sigset_t.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timeval.h \
  /usr/include/x86_64-linux-gnu/bits/types/struct_timespec.h \
  /usr/include/x86_64-linux-gnu/bits/select2.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes.h \
  /usr/include/x86_64-linux-gnu/bits/thread-shared-types.h \
  /usr/include/x86_64-linux-gnu/bits/pthreadtypes-arch.h \
  /usr/include/x86_64-linux-gnu/bits/atomic_wide_counter.h \
  /usr/include/x86_64-linux-gnu/bits/struct_mutex.h \
  /usr/include/x86_64-linux-gnu/bits/struct_rwlock.h \
  /usr/include/elf.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/rbtree.h \
  /usr/include/linux/stddef.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/jhash.h \
  /home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/include/linux/unaligned/packed_struct.h \

/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/weak.o: $(deps_/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/weak.o)

$(deps_/home/utkarsh/Documents/Linux-Kernel/newKernel/linux-6.3.6/tools/objtool/weak.o):
